name: docs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  visualize: # https://githubnext.com/projects/repo-visualization
    strategy:
      matrix:
        go-version: [1.23.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    permissions:
      contents: write # Grants permission to push changes
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Update diagram
      uses: githubocto/repo-visualizer@0.7.1
      with:
        commit_message: "docs: Repo visualizer: updated diagram"
        output_file: "docs/diagram.svg"
